git:
  baseurl: https://github.com
  prefix: fepitre/qubes-
  branch: builderv2
  maintainers:
    - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2

backend-vmm: xen

debug: true
verbose: true
qubes-release: r4.2

reuse-fetched-source: true


use-qubes-repo:
  version: 4.1
  testing: false

gpg-client: qubes-gpg-client-wrapper

sign-key:
  rpm: 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6
  deb: 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6

distributions:
  - host-fc32
  - vm-bullseye
  - vm-fc35

templates:
  - fedora-35-xfce:
      dist: fc35
      flavor: xfce
  - debian-11:
      dist: bullseye
      options:
        - standard
        - firmware
  - whonix-gateway-16:
      dist: bullseye
      flavor: whonix-gateway
      options:
        - minimal
        - no-recommends
  - whonix-workstation-16:
      dist: bullseye
      flavor: whonix-workstation
      options:
        - minimal
        - no-recommends
artifacts-dir: /home/user/qubes-builderv2/artifacts

components:
  - lvm2
  - vmm-xen
  - core-libvirt
  - core-vchan-xen
  - core-qubesdb
  - core-qrexec
  - linux-utils
  - python-cffi
  - python-xcffib
  - python-objgraph
  - python-hid
  - python-u2flib-host
  - python-qasync
  - python-panflute
  - rpm-oxide
  - core-admin
  - core-admin-client
  - core-admin-addon-whonix
  - core-admin-linux
  - core-agent-linux
  - intel-microcode
  - linux-firmware
  - linux-kernel
  - artwork
  - grub2
  - grub2-theme
  - gui-common
  - gui-daemon
  - gui-agent-linux
  - gui-agent-xen-hvm-stubdom
  - seabios
# FIXME: we need to handle the case of having sha1sum files
#  - vmm-xen-stubdom-legacy
#  - vmm-xen-stubdom-linux
  - app-linux-split-gpg
  - app-thunderbird
  - app-linux-pdf-converter
  - app-linux-img-converter
  - app-linux-input-proxy
  - app-linux-usb-proxy
  - app-linux-snapd-helper
  - app-shutdown-idle
  - app-yubikey
  - app-u2f
  - screenshot-helper
  - repo-templates
  - meta-packages
  - manager
  - desktop-linux-common
  - desktop-linux-kde
  - desktop-linux-xfce4
  - desktop-linux-xfce4-xfwm4
  - desktop-linux-i3
  - desktop-linux-i3-settings-qubes
  - desktop-linux-awesome
  - desktop-linux-manager
  - grubby-dummy
  - dummy-psu
  - dummy-backlight
  - xorg-x11-drv-intel
  - linux-gbulb
# FIXME: we need to handle the case of downloading detached signature of hash
#  - linux-scrypt
  - qubes-release
  - pykickstart
  - blivet
  - lorax
  - lorax-templates
  - anaconda
  - anaconda-addon
  - tpm-extra
  - trousers-changer
  - antievilmaid
  - xscreensaver
  - remote-support
  - xdotool

less-secure-signed-commits-sufficient:
  - lvm2
  - vmm-xen
  - core-libvirt
  - core-vchan-xen
  - core-qubesdb
  - core-qrexec
  - linux-utils
  - python-cffi
  - python-xcffib
  - python-objgraph
  - python-hid
  - python-u2flib-host
  - python-qasync
  - python-panflute
  - rpm-oxide
  - core-admin
  - core-admin-client
  - core-admin-addon-whonix
  - core-admin-linux
  - core-agent-linux
  - intel-microcode
  - linux-firmware
  - linux-kernel
  - artwork
  - grub2
  - grub2-theme
  - gui-common
  - gui-daemon
  - gui-agent-linux
  - gui-agent-xen-hvm-stubdom
  - seabios
  - vmm-xen-stubdom-legacy
  - vmm-xen-stubdom-linux
  - app-linux-split-gpg
  - app-thunderbird
  - app-linux-pdf-converter
  - app-linux-img-converter
  - app-linux-input-proxy
  - app-linux-usb-proxy
  - app-linux-snapd-helper
  - app-shutdown-idle
  - app-yubikey
  - app-u2f
  - screenshot-helper
  - repo-templates
  - meta-packages
  - manager
  - desktop-linux-common
  - desktop-linux-kde
  - desktop-linux-xfce4
  - desktop-linux-xfce4-xfwm4
  - desktop-linux-i3
  - desktop-linux-i3-settings-qubes
  - desktop-linux-awesome
  - desktop-linux-manager
  - grubby-dummy
  - dummy-psu
  - dummy-backlight
  - xorg-x11-drv-intel
  - linux-gbulb
  - linux-scrypt
  - qubes-release
  - pykickstart
  - blivet
  - lorax
  - lorax-templates
  - anaconda
  - anaconda-addon
  - tpm-extra
  - trousers-changer
  - antievilmaid
  - xscreensaver
  - remote-support
  - xdotool

repository-publish:
  components: current-testing
  templates: templates-itl-testing

repository-upload-remote-host:
  rpm: user@qubes.notset.fr/repo/notset/rpm/
  deb: user@qubes.notset.fr/repo/notset/deb/

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"
#    clean: false

#executor:
#  type: qubes
#  options:
#    dispvm: "qubes-builder-dvm"

stages:
  - fetch:
      executor:
        type: docker
        options:
          image: "qubes-builder-fedora:latest"
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
