git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-

backend-vmm: xen

debug: true
verbose: true
qubes-release: r4.2

reuse-fetched-source: true

use-qubes-repo:
  version: 4.1
  testing: false

gpg-client: qubes-gpg-client-wrapper

sign-key:
  rpm: 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6
  deb: 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6

distributions:
  - host-fc32
  - vm-bullseye
  - vm-fc35

templates:
  - fedora-35-xfce:
      dist: fc35
      flavor: xfce
  - debian-11:
      dist: bullseye
      options:
        - standard
        - firmware
  - whonix-gateway-16:
      dist: bullseye
      flavor: whonix-gateway
      options:
        - minimal
        - no-recommends
  - whonix-workstation-16:
      dist: bullseye
      flavor: whonix-workstation
      options:
        - minimal
        - no-recommends
artifacts-dir: /home/user/qubes-builderv2/artifacts

components:
  - python-qasync:
      url: https://github.com/fepitre/qubes-python-qasync
      branch: builderv2
      maintainers:
        - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2
  - core-vchan-xen:
      url: https://github.com/fepitre/qubes-core-vchan-xen
      branch: builderv2
      maintainers:
        - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2
  - core-qrexec:
      url: https://github.com/fepitre/qubes-core-qrexec
      branch: builderv2
      maintainers:
        - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2
  - desktop-linux-xfce4-xfwm4:
      url: https://github.com/fepitre/qubes-desktop-linux-xfce4-xfwm4
      branch: builderv2
      maintainers:
        - 9FA64B92F95E706BF28E2CA6484010B5CDC576E2

less-secure-signed-commits-sufficient:
  - python-qasync
  - core-vchan-xen
  - core-qrexec
  - desktop-linux-xfce4-xfwm4

repository-publish:
  components: current-testing
  templates: templates-itl-testing

repository-upload-remote-host:
  rpm: user@qubes.notset.fr/repo/notset/rpm/
  deb: user@qubes.notset.fr/repo/notset/deb/

executor:
  type: docker
  options:
    image: "qubes-builder-fedora:latest"

#executor:
#  type: qubes
#  options:
#    dispvm: "qubes-builder-dvm"

stages:
  - fetch:
      executor:
        type: docker
        options:
          image: "qubes-builder-fedora:latest"
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
