include:
  - example-configs/qubes-os-r4.2.yml

git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: master

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.2
build_timeout: 21600

reuse-fetched-source: true
do-merge: true
fetch-versions-only: true

distributions:
  - host-fc32

+components:
  - kernel-latest:
      url: https://github.com/QubesOS/qubes-linux-kernel
      branch: master
  - release-configs

executor:
  type: qubes
  options:
    dispvm: "qubes-builder-dvm"

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
